services:
  postgres:
    image: postgres:15
    container_name: pg_course
    environment:
      POSTGRES_DB: pvz
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_pass
    ports:
      - "5444:5432"
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d pvz" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  flyway:
    image: flyway/flyway
    depends_on:
      postgres:
        condition: service_healthy
    command:
      - "migrate"
      - "-baselineOnMigrate=true"
    volumes:
      - ./db/migrations:/flyway/sql
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/pvz
      FLYWAY_USER: admin
      FLYWAY_PASSWORD: admin_pass
      FLYWAY_BASELINE_VERSION: 1
      FLYWAY_BASELINE_DESCRIPTION: "Initial baseline"
      FLYWAY_SCHEMAS: public

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://admin:admin_pass@postgres:5432/pvz?sslmode=disable"
    volumes:
      - ./queries.yaml:/queries.yaml
    command:
      - "--extend.query-path=/queries.yaml"
      - "--collector.stat_statements"
      - "--collector.stat_statements.query_length=300"
      - "--collector.stat_statements.limit=500"
    ports:
      - "9187:9187"
    depends_on:
      - postgres

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - postgres_exporter

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  pg_data:
  grafana_data: