### Add one document
POST http://localhost:8080/api/add
Content-Type: text/plain; charset=utf-8

Индексы B-Tree хорошо подходят для точных совпадений и сортировки данных.

### Add batch documents
POST http://localhost:8080/api/add-batch
Content-Type: text/plain; charset=utf-8

Индексы B-Tree отлично подходят для поиска точных совпадений и сортировки данных.;VACUUM очищает таблицу от мертвых строк, предотвращая раздувание файлов.;Команда EXPLAIN ANALYZE показывает реальный план выполнения запроса и затраченное время.;PgBouncer снижает нагрузку на PostgreSQL при большом количестве клиентов.;Партицирование таблиц ускоряет удаление старых данных и улучшает производительность выборок.;Материализованные представления сохраняют результаты сложных агрегаций для быстрого чтения.;Увеличение work_mem позволяет использовать больше оперативной памяти для сортировки и хеширования.;Write-Ahead Log обеспечивает надежность данных и используется для репликации.;Для поиска по геометрическим объектам и координатам используют GiST или SP-GiST.;Триггеры автоматически выполняют функции при вставке или обновлении записей.;JSONB хранит документы в бинарном формате и ускоряет доступ к ключам.;shared_buffers определяет, сколько данных PostgreSQL кэширует в памяти.

### Search: indexes/forms
GET http://localhost:8080/api/search?query=как%20искать%20по%20формам

### Search: cleaning data
GET http://localhost:8080/api/search?query=как%20улучшить%20очистку%20данных

### Search: RAM settings
GET http://localhost:8080/api/search?query=как%20увеличить%20настройку%20ОЗУ

### Search: query plan
GET http://localhost:8080/api/search?query=как%20посмотреть%20план%20выполнения%20запроса
